---
- name: Setup Kafka
  hosts: kafka
  remote_user: ubuntu
  sudo: yes
  tasks:
  - name: Copy helper script
    copy:
      src: /home/ubuntu/helper.sh
      dest: /home/ubuntu/helper.sh
  - name: Transfer and execute the setup script
    script: /home/ubuntu/setup_kafka.sh
